apiVersion: v2
appVersion: '1.0'
description: A Helm chart for labs-Kamil-Biegaj-HM-nodejs App
name: labs-Kamil-Biegaj-HM-nodejs
home: https://github.com/hmcts/labs-Kamil-Biegaj-HM-nodejs
version: 0.0.7
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
