nodejs:
  applicationPort: 8080
  aadIdentityName: labs
  ingressHost: labs-Kamil-Biegaj-HM-nodejs.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/labs/Kamil-Biegaj-HM-nodejs:latest'
  #  Uncomment once the vault containing the app insights key has been set up
  #  keyVaults:
  #    labs:
  #      secrets:
  #        - AppInsightsInstrumentationKey
  environment:
